version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=3002
      - ENABLE_DOCS=true
      - DATABASE_URL=mongodb://mongo:27017/gesclient
      # Ajoute ici d'autres variables d'env si besoin
    restart: unless-stopped
    command: node src/app.js

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: 